### ISSUE TITLE
hashtag `#` is comment when extended mode is enabled `(?x)`

### ISSUE THREAD

**Issue by RedCMD** [jtbandes/swift-tmlanguage#1]
the `#(?<name>(?:[^#]|##)*)#` section is commented out
![image](https://github.com/jtbandes/swift-tmlanguage/assets/33529441/06ad1582-b8b8-48d7-9618-f1ab26ea8d7a)
https://github.com/jtbandes/swift-tmlanguage/blob/4028d24f926bccca29204528ee97ecd455d5908e/Swift.tmLanguage.yaml#L1967

you will need to backslash all hashtags `#`
![image](https://github.com/jtbandes/swift-tmlanguage/assets/33529441/e21e7814-c326-4c60-9401-43a02c7f4306)

also remember to add in its corresponding scope name
`9: { name: entity.name.function.callout.regexp }`

**Comment by jtbandes** [comment]
Awesome, thank you! How did you find this?

Fixing in: https://github.com/jtbandes/swift-tmlanguage/pull/2

I think I must've made this mistake because the TextMate bundle editor does not highlight it as a comment. (And obviously I got lazy in adding test cases 😉)

<img width="560" alt="image" src="https://github.com/jtbandes/swift-tmlanguage/assets/14237/3a222ece-7872-4646-b49f-2a14a75f7cdc">

This makes me wonder if there are any other instances of the same thing elsewhere in the grammar...

**Comment by RedCMD** [comment]
was having a quick scroll through your grammar; reading the comments
and noticed that it was commented out
assumed it wasn't intentional

**Comment by jtbandes** [comment]
Amusingly they have decided to support a superset of several dialects… so it was a lot of work to try and cover everything here. The implementation is still a work in progress though. https://github.com/apple/swift-evolution/blob/main/proposals/0355-regex-syntax-run-time-construction.md#syntax
